Update README.md
dougg3/obs-ios-camera-source pull request #22
Opened 2023-06-17 19:16 UTC by jaco129

For my arch (SteamOS) install I had to install the ffmpeg package or else compilation would fail due to missing libavcodec.

2023-06-18 05:44 UTC, dougg3 requested changes
Hi @jaco129 ,

Thanks for your contribution! Normally the process of installing OBS in Arch forces the `ffmpeg` package (or possibly `ffmpeg-obs`) to automatically be installed. I'm guessing something about the way you installed OBS on SteamOS didn't cause this to happen.

I hesitate to put this in the instructions for everyone on Arch-based distros to follow because it causes problems with normal Arch if I install OBS through the Arch User Repository using the linked instructions from the README. In that case, it actually installs its own `ffmpeg-obs` package that conflicts with `ffmpeg`, and running your updated command results in the following prompt:

`ffmpeg and ffmpeg-obs are in conflict. Remove ffmpeg-obs? [y/N]`

If I say yes, it fails:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: removing ffmpeg-obs breaks dependency 'ffmpeg-obs>=6' required by obs-studio-browser
```

If I say no, it also fails:

```
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: ffmpeg and ffmpeg-obs are in conflict
```

Rather than updating the command under the Arch section for everybody, what do you think about adding another little blurb below about possibly also needing to install ffmpeg on SteamOS? Or maybe a separate section just for SteamOS? Could you update this PR to do one of those instead? Thanks!

2023-06-19 17:07 UTC, jaco129 commented
Ah interesting! Adding a note specific to SteamOS sounds great to me. I'll amend that commit and update this PR soon.

Thanks!

2023-06-19 17:28 UTC, jaco129 commented
Done  👍

2023-06-19 17:32 UTC, dougg3 commented
This looks great. Thank you!

2023-06-19 17:35 UTC, merged